services: 
  laravel_web:
    build: 
      context: .
      dockerfile: laravel.Dockerfile
    container_name: laravel_web
    ports:
      - "5432:80"
    volumes:
      - ${LARAVEL_DIR}:/var/www/html
    networks:
      - 001-network
    env_file:
      .env
  laravel_db:
    image: mariadb:latest
    container_name: laravel_db
    ports:
      - "33306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    networks:
      - 001-network

networks:
  001-network:
    name: 001-network