services: 
  laravel:
    build: 
      context: .
      dockerfile: laravel.Dockerfile
    container_name: laravel
    ports:
      - "5432:80"
    volumes:
      - ${LARAVEL_DIR}:/var/www/html
    networks:
      - 001-network
    env_file:
      .env

networks:
  001-network:
    name: 001-network